#!/usr/bin/env python3
"""Generate emoji.js: a flat array of {char, name, keywords} usable from QML.

Sources only stdlib (unicodedata) so no fetch required.
Output: emoji.js next to this script. Re-run when Python's Unicode data is updated.
"""
import json
import unicodedata
from pathlib import Path

# Curated codepoint ranges covering the practical emoji set. Skips most flags
# (regional indicators) and skin-tone modifiers since unicodedata names are
# unhelpful for them.
RANGES = [
    (0x00A9, 0x00AE),    # ©®
    (0x203C, 0x2049),
    (0x20E3, 0x20E3),
    (0x2122, 0x2122),
    (0x2139, 0x2139),
    (0x2194, 0x2199),
    (0x21A9, 0x21AA),
    (0x231A, 0x231B),
    (0x2328, 0x2328),
    (0x23CF, 0x23CF),
    (0x23E9, 0x23F3),
    (0x23F8, 0x23FA),
    (0x24C2, 0x24C2),
    (0x25AA, 0x25AB),
    (0x25B6, 0x25B6),
    (0x25C0, 0x25C0),
    (0x25FB, 0x25FE),
    (0x2600, 0x27BF),
    (0x2934, 0x2935),
    (0x2B05, 0x2B07),
    (0x2B1B, 0x2B1C),
    (0x2B50, 0x2B50),
    (0x2B55, 0x2B55),
    (0x3030, 0x3030),
    (0x303D, 0x303D),
    (0x3297, 0x3297),
    (0x3299, 0x3299),
    (0x1F004, 0x1F004),
    (0x1F0CF, 0x1F0CF),
    (0x1F170, 0x1F251),
    (0x1F300, 0x1F6FF),
    (0x1F7E0, 0x1F7EB),
    (0x1F900, 0x1F9FF),
    (0x1FA70, 0x1FAFF),
]

KEYWORD_HINTS = {
    "FACE": "smiley emotion",
    "HEART": "love",
    "STAR": "favorite",
    "FIRE": "hot lit",
    "ROCKET": "launch space",
    "CHECK": "yes ok done",
    "CROSS": "no error",
    "WARNING": "caution alert",
    "THUMBS UP": "yes good +1 like",
    "THUMBS DOWN": "no bad -1 dislike",
    "HUNDRED": "100 perfect",
    "PARTY": "celebrate",
}


def derive_keywords(name: str) -> str:
    extras = []
    for k, v in KEYWORD_HINTS.items():
        if k in name:
            extras.append(v)
    return " ".join(extras)


def main() -> None:
    out = []
    seen = set()
    for lo, hi in RANGES:
        for cp in range(lo, hi + 1):
            ch = chr(cp)
            try:
                name = unicodedata.name(ch)
            except ValueError:
                continue
            if ch in seen:
                continue
            seen.add(ch)
            out.append({
                "c": ch,
                "n": name.lower(),
                "k": derive_keywords(name),
            })

    out.sort(key=lambda e: e["n"])
    target = Path(__file__).parent / "emoji.js"
    body = (
        ".pragma library\n\n"
        "// Auto-generated by gen-emoji.py: do not edit by hand.\n"
        "// Re-run: python3 gen-emoji.py\n"
        f"var EMOJIS = {json.dumps(out, ensure_ascii=False)};\n"
    )
    target.write_text(body, encoding="utf-8")
    print(f"wrote {len(out)} emojis to {target}")


if __name__ == "__main__":
    main()
